version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
      time: "00:30"
      timezone: "Europe/Madrid"
    rebase-strategy: "disabled"
    assignees:
      - "ClaudiodelaRiva"
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
      time: "00:30"
      timezone: "Europe/Madrid"
    rebase-strategy: "disabled"
    assignees:
      - "ClaudiodelaRiva"
    open-pull-requests-limit: 20