services:

  social-graph-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-social-graph-service
    hostname: social-graph-service
    depends_on:
      - jaeger-agent
      - social-graph-mongodb
    restart: always
    entrypoint: SocialGraphService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  social-graph-mongodb:
    image: mongo:4.4.6
    container_name: ${TJOB_NAME}-social-graph-mongodb
    hostname: social-graph-mongodb
    restart: always
    networks:
      - jenkins_network

  social-graph-redis:
    build:
      context: ./sut/docker/redis
    image: redis:socialnetwork
    container_name: ${TJOB_NAME}-social-graph-redis
    hostname: social-graph-redis
    restart: always
    networks:
      - jenkins_network

  home-timeline-redis:
    build:
      context: ./sut/docker/redis
    image: redis:socialnetwork
    container_name: ${TJOB_NAME}-home-timeline-redis
    hostname: home-timeline-redis
    restart: always
    networks:
      - jenkins_network

  compose-post-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-compose-post-service
    hostname: compose-post-service
    restart: always
    depends_on:
      - jaeger-agent
    entrypoint: ComposePostService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  compose-post-redis:
    build:
      context: ./sut/docker/redis
    image: redis:socialnetwork
    container_name: ${TJOB_NAME}-compose-post-redis
    hostname: compose-post-redis
    restart: always
    networks:
      - jenkins_network

  post-storage-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-post-storage-service
    hostname: post-storage-service
    restart: always
    depends_on:
      - jaeger-agent
      - post-storage-mongodb
    entrypoint: PostStorageService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  post-storage-memcached:
    build:
      context: ./sut/docker/memcached
    image: memcached:socialnetwork
    container_name: ${TJOB_NAME}-post-storage-memcached
    hostname: post-storage-memcached
    restart: always
    networks:
      - jenkins_network

  post-storage-mongodb:
    image: mongo:4.4.6
    container_name: ${TJOB_NAME}-post-storage-mongodb
    hostname: post-storage-mongodb
    restart: always
    networks:
      - jenkins_network

  user-timeline-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-user-timeline-service
    hostname: user-timeline-service
    restart: always
    depends_on:
      - jaeger-agent
      - user-timeline-mongodb
    entrypoint: UserTimelineService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  user-timeline-redis:
    build:
      context: ./sut/docker/redis
    image: redis:socialnetwork
    container_name: ${TJOB_NAME}-user-timeline-redis
    hostname: user-timeline-redis
    restart: always
    networks:
      - jenkins_network

  user-timeline-mongodb:
    image: mongo:4.4.6
    container_name: ${TJOB_NAME}-user-timeline-mongodb
    hostname: user-timeline-mongodb
    restart: always
    networks:
      - jenkins_network

  url-shorten-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-url-shorten-service
    hostname: url-shorten-service
    restart: always
    entrypoint: UrlShortenService
    depends_on:
      - jaeger-agent
      - url-shorten-mongodb
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  url-shorten-memcached:
    build:
      context: ./sut/docker/memcached
    image: memcached:socialnetwork
    container_name: ${TJOB_NAME}-url-shorten-memcached
    hostname: url-shorten-memcached
    restart: always
    networks:
      - jenkins_network

  url-shorten-mongodb:
    image: mongo:4.4.6
    container_name: ${TJOB_NAME}-url-shorten-mongodb
    hostname: url-shorten-mongodb
    restart: always
    networks:
      - jenkins_network

  user-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-user-service
    hostname: user-service
    restart: always
    depends_on:
      - jaeger-agent
      - user-mongodb
    entrypoint: UserService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  user-memcached:
    build:
      context: ./sut/docker/memcached
    image: memcached:socialnetwork
    container_name: ${TJOB_NAME}-user-memcached
    hostname: user-memcached
    restart: always
    networks:
      - jenkins_network

  user-mongodb:
    image: mongo:4.4.6
    container_name: ${TJOB_NAME}-user-mongodb
    hostname: user-mongodb
    restart: always
    networks:
      - jenkins_network

  media-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-media-service
    hostname: media-service
    depends_on:
      - jaeger-agent
      - media-mongodb
    restart: always
    entrypoint: MediaService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  media-memcached:
    build:
      context: ./sut/docker/memcached
    image: memcached:socialnetwork
    container_name: ${TJOB_NAME}-media-memcached
    hostname: media-memcached
    restart: always
    networks:
      - jenkins_network

  media-mongodb:
    image: mongo:4.4.6
    container_name: ${TJOB_NAME}-media-mongodb
    hostname: media-mongodb
    restart: always
    networks:
      - jenkins_network

  text-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-text-service
    hostname: text-service
    restart: always
    depends_on:
      - jaeger-agent
    entrypoint: TextService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  unique-id-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-unique-id-service
    hostname: unique-id-service
    restart: always
    depends_on:
      - jaeger-agent
    entrypoint: UniqueIdService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  user-mention-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-user-mention-service
    hostname: user-mention-service
    depends_on:
      - jaeger-agent
    restart: always
    entrypoint: UserMentionService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  home-timeline-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-home-timeline-service
    hostname: home-timeline-service
    depends_on:
      - jaeger-agent
    restart: always
    entrypoint: HomeTimelineService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  write-home-timeline-service:
    build:
      context: ./sut
      dockerfile: Dockerfile
    image: social-network-microservices:socialnetwork
    container_name: ${TJOB_NAME}-write-home-timeline-service
    hostname: write-home-timeline-service
    depends_on:
      - jaeger-agent
      - write-home-timeline-rabbitmq
    restart: always
    entrypoint: WriteHomeTimelineService
    volumes:
      - ./sut/config:/social-network-microservices/config
    networks:
      - jenkins_network

  write-home-timeline-rabbitmq:
    build:
      context: ./sut/docker/rabbitmq
    image: rabbitmq:socialnetwork
    container_name: ${TJOB_NAME}-write-home-timeline-rabbitmq
    hostname: write-home-timeline-rabbitmq
    restart: always
    networks:
      - jenkins_network

  nginx-thrift:
    build:
      context: ./sut/docker/openresty-thrift
      dockerfile: xenial/Dockerfile
      network: host
    image: openresty-thrift:socialnetwork
    container_name: ${TJOB_NAME}-nginx-thrift
    hostname: nginx-thrift
    ports:
      - ${frontend_port}:8080
    depends_on:
      - jaeger-agent
    restart: always
    volumes:
      - ./sut/nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./sut/nginx-web-server/pages:/usr/local/openresty/nginx/pages
      - ./sut/nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./sut/nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
      - ./sut/gen-lua:/gen-lua
      - ./sut/docker/openresty-thrift/lua-thrift:/usr/local/openresty/lualib/thrift
    networks:
      - jenkins_network

  jaeger-agent:
    build:
      context: ./sut/docker/jaeger
    image: jaeger-agent:socialnetwork
    container_name: ${TJOB_NAME}-jaeger-agent
    hostname: jaeger-agent
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - jenkins_network

networks:
  jenkins_network:
    external: true
